Auth pages, Input and BoxWrapper components, form validation
Belfast-LSA-team/DwarfthStone pull request #8
Opened 2021-03-24 11:44 UTC by LStaynov

2021-03-24 23:40 UTC, resdenia reviewed
Хорошо продумана валидация!

2021-03-24 23:40 UTC, resdenia commented on client/src/components/inputField/InputField.tsx
> +            <span className="input-error">{error}</span>
Я думаю что может не стоит добавлять лишний пустой тег думаю будет хорошо если он будет прорисовываться если ошибка возникает.

2021-03-24 23:40 UTC, resdenia commented on client/src/pages/auth/Auth.tsx
> +            console.log("Отправили форму");
Обработчик ошибки если ответ с API пришел не верный(В дальнейшем нужно будет передавать сообщение в generalError) но на данном этапе можно сделать отправку формы и обработать ошибку(через консоль лог)

2021-03-24 23:40 UTC, resdenia commented on client/src/pages/auth/Auth.tsx
> +                    <InputField
Тут я думаю можно оптимизировать через итеракцию. Есть повторные элементы
```
renderInputs =()=>{
	return 	initialFormValues.map(input=>{
		return (<InputField
				className="auth__input"
				type={input.type}
				value={formValues[input.name]}
				stretch={input.stretch}
....
			/>)
	})
```

2021-03-24 23:40 UTC, resdenia commented on client/src/pages/auth/Auth.tsx
> +                  login: "",
Было бы удобно тут добавить  больше информации к полям к примеру `login:{placeholder:'Логин',type:'text'}...`
Для того что б потом использовать в  renderInput

2021-03-24 23:40 UTC, resdenia commented on client/src/components/gamelayout/gamelayout.css
> +    height: 100vh;
Не очень хороший вариант для  респонсив.

2021-03-25 03:22 UTC, Jarith reviewed
Авторизация и регистрация - две разные страницы и лучше не смешивать их разметку в один компонент. Он уже получился очень большим и трудным для восприятия. В будущем еще будут проблемы с тем, чтобы написать на него тесты

2021-03-25 03:22 UTC, Jarith commented on client/src/components/boxwrapper/BoxWrapper.tsx
> +import React from "react";
Можно сразу импортировать `Fragment`

```suggestion
import React, {Fragment} from "react";
```

2021-03-25 03:22 UTC, Jarith commented on client/src/components/boxwrapper/BoxWrapper.tsx
> +    const { className, isModal, children } = props;
Пропс `isModal` нигде не используется

2021-03-25 03:22 UTC, Jarith commented on client/src/components/gamelayout/GameLayout.tsx
> +                <div className="background"></div>
Не вижу необходимости в пустом теге. Может быть просто задать `background-color` для родительского `<div>`?

2021-03-25 03:39 UTC, Jarith requested changes
Реализовывать руками формы и валидации потренировались в первом модуле. На текущем проекте предлагаю все же по большей части использовать продакшн-решения.
Для форм предлагаю взять [react-final-form](https://final-form.org/react)

2021-03-25 11:18 UTC, LStaynov commented on client/src/pages/auth/Auth.tsx
> +            console.log("Отправили форму");
Предлагаю вынести интеграцию с апи в отдельный таск, уже получается большой ПР.

2021-03-26 19:13 UTC, merged