Add modal component
Belfast-LSA-team/DwarfthStone pull request #9
Opened 2021-03-24 18:25 UTC by gutskalss

2021-03-24 23:38 UTC, resdenia commented on client/src/utils/toggleElement.ts
> +            element.style.removeProperty("display");
Ты удаляешь ` display: flex;`
```
.modal {
    position: fixed;
    top: 0;
    left: 0;
    width: 100vw;
    height: 100vh;
    background-color: rgba(0, 0, 0, 0.4);
    display: flex;
    justify-content: center;
    align-items: center;
    z-index: 10000;
}
```

Может можем переделать эту функцию что б потом ее как-то переиспользовать?
Что б делать toggle можем делать в проекте dark | light.  Или тут больше подойдет isShow (название функции) не идеально но можно додумать если будем оставлять эту реализацию. 

Или как вариант убрать перебор стилей и можно добавить доп класс => modal modal__is-visible  и тоглить сам класс  modal__is-visible. И можно это унифицировать что б потом тоглить классы как  dark | light

2021-03-24 23:38 UTC, resdenia commented on client/src/components/modal/Modal.tsx
> +            {children}
Так-же есть вероятность конфликта что когда будет нажат  внутренний див будет тоже обрабатываться onclick для верхнего дива. Я думаю что можно разделить  тело модалки и  backdrop(черной подложки)

2021-03-24 23:38 UTC, resdenia commented on client/src/utils/toggleElement.ts
> +    const element: HTMLElement | null = document.querySelector(elementSelector);
Нужно учесть если будет несколько  modal на одной странице. Пока что будет реализоваться  только ближайшее модальное окно.

2021-03-25 03:10 UTC, Jarith requested changes
Если пишем на реакте (или любом другом фреймворке), то не стоит напрямую взаимодействовать с DOM-деревом.

Вообще, реализация модалки немного нетривиальная задача и лучше воспользоваться готовыми библиотеками. Например [react-modal](https://github.com/reactjs/react-modal)

2021-03-25 04:08 UTC, gutskalss commented on client/src/utils/toggleElement.ts
> +            element.style.removeProperty("display");
Да, эту функцию уже можно использовать для других элементов. Она не совсем так работает, как ты подумал. В случае выше она не убирает свойство `display: flex;`, она проверяет если у блока указано в инлайн стилях свойство display (в нашем случае это будет `display: none;`), если оно есть, функция его убирает, если его нет, она его добавляет. Можно сделать это дополнительным классом `hide`. Я так делал в предыдущем проекте, но тут решил попробовать так.

2021-03-25 04:09 UTC, gutskalss commented on client/src/components/modal/Modal.tsx
> +            {children}
Я проверил) Такого происходить не будет)

2021-04-11 19:20 UTC, Jarith approved these changes

2021-04-11 19:20 UTC, merged